sudo: required

stages:
  - name: publish
    if: branch = master AND type = push

jobs:
  include:
    - name: Publish new versions
      stage: publish
      script:
        - ./scripts/publish-new.sh
